POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "more testing",
  "description": "at 6pm"
}

###

GET http://localhost:3000/api/todos

###

POST http://localhost:3000/api/auth/sign-in/email
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

